---
title: "Predicting the manner of belldrum excercises"
author: "Bernhard Thoni"
date: "February 22, 2015"
output:
  html_document:
    fig_caption: yes
    highlight: espresso
    number_sections: yes
    theme: cosmo
    toc: yes
---


## Here loading necessary libraries
```{r}
library(lattice)
library(ggplot2)
library(stats)
library(foreign)
library(caret)
library(rpart)
library(randomForest)
```

## Here importing the data 
```{r}
data_validate<-read.csv("data//pml-testing.csv",header = T,na.strings = c(""," ","NA","#DIV/0!"),strip.white=T)
data_samples<-read.csv("data//pml-training.csv",header = T,na.strings = c(""," ","NA"),strip.white=T)
```

## Here cleaning the data
```{r}
colneed2goIN<-which(colSums(is.na(data_samples))>19000) #find those with more than 19000 NAs
data_samples_clean_tmp1<-data_samples[,-c(colneed2goIN)] #sort those NAs out
data_samples_clean_tmp2<-data_samples_clean_tmp1[,-c(1:7)] #sort column 1 to 7 out, as inneccesary for model/pr
dsclean<-data_samples_clean_tmp2
```

## Here partitioning the data
```{r}
set.seed(13323) #for reproducability
inTrain<-createDataPartition(y=dsclean$classe, p=0.7,list=FALSE)
training<-dsclean[inTrain,]
testing<-dsclean[-inTrain,]
```

## Here fitting different models with training data
```{r}
#modFit_rpart<-rpart(classe ~ .,data=training)
#modFit_glm<-train(classe~.,method="glm",data=training)
modFit_rforest<-randomForest(formula=classe~.,data=training,ntree=500)
#looking at some figures first, before we accept the modFit_rforest
modFit_rforest$confusion
modFit_rforest$importance
head(round(modFit_rforest$err.rate,5),100) #shortened! otherwise, way too long
head(modFit_rforest$votes,200) #shortened! otherwise, way too long for report
```

## Here predicting on training/testing, respectively validation-data
```{r}
### first: check that colnames of training/testing and validate match!!!
# pred_testing<-predict(modFit_rpart,newdata=testing,type="class")
pred_testing<-predict(modFit_rforest,testing)
table(pred_testing,testing$classe)

### crossvalidation, but not quite sure, how to interpret this rightly
training_s<-training[,c(1:52)]
my_rfcv<-rfcv(training_s,training$classe,cv.fold=5)

### finally predict on validation-data for latter submission
pred_validate<-predict(modFit_rforest,data_validate)
pred_validate_as_char<-as.character(pred_validate)
```

## helper function for submitting + final submission
```{r}
# requirement therefore: x must be char-vector in form of: answers <- rep("A", 20)
pml_write_files = function(x){
  n = length(x)
  for(i in 1:n){
    filename = paste0("results//problem_id_",i,".txt")
    write.table(x[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
  }
}

###
### generating 20 files for submission from my vector of chars
pml_write_files(pred_validate_as_char)
```
